hl.on("hyprland.start", function()
	hl.exec_cmd("waybar -c ~/.config/waybar/config.jsonc")
	hl.exec_cmd("waybar -c ~/.config/waybar/configtop.jsonc")
	hl.exec_cmd("dunst")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("awww img -o DP-3 /home/kevinji2/wallpapers/pusheen.jpg")
	hl.exec_cmd("awww img -o eDP-1 /home/kevinji2/wallpapers/pusheen.jpg")
	hl.exec_cmd("exec swayosd-server")
	hl.exec_cmd("darkman run")
	hl.exec_cmd("darkman set dark")
end)
